### PR TITLE
Refactor and cleanup

### PR DESCRIPTION
**Pull request by dmikurube**
A set of simple refactoring and cleanup.

### CODE REVIEW

**Comment by trung-huynh** [comment]
@dmikurube, this PR might conflict with https://github.com/embulk/embulk-util-text/pull/5? The 5th PR is updating the class definition.

**Comment by dmikurube** [comment]
@trung-huynh Those PRs 1-8 are actually in a sequence. You can see the following PR metadata at the top of each PR :

* #5 is `remove-task-defining-interfaces` merged into `boilerplates` ( == #4).
* #4 is `boilerplates` merged into `refactor` ( == #3).

Then, they shouldn't conflict. :)

**Review by trung-huynh — APPROVED** [review]
LGTM

**Comment by trung-huynh** [comment]
@dmikurube , realized that 👍 .

**Comment by dmikurube** [comment]
Thanks!

**Pull request merged**
